=== SalmanSiddique/ZorbaXQuery/flight.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://tempuri.org/flight" elementFormDefault="qualified" targetNamespace="http://tempuri.org/flight" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="travel">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="airport" />
        <xs:element ref="flight" />
        <xs:element ref="passenger" />
        <xs:element ref="reservation" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="airport">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" />
      </xs:sequence>
      <xs:attribute name="code" type="xs:ID" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string" />
  <xs:element name="flight">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="date" />
        <xs:element ref="departureTime" />
        <xs:element ref="arrivalTime" />
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required" />
      <xs:attribute name="from" type="xs:IDREF" use="required" />
      <xs:attribute name="to" type="xs:IDREF" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="date" type="xs:string" />
  <xs:element name="departureTime" type="xs:string" />
  <xs:element name="arrivalTime" type="xs:string" />
  <xs:element name="passenger">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" />
        <xs:element ref="address" />
      </xs:sequence>
      <xs:attribute name="ssn" type="xs:ID" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="address" type="xs:string" />
  <xs:element name="reservation">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="creditcard" />
      </xs:sequence>
      <xs:attribute name="passenger" type="xs:IDREF" use="required" />
      <xs:attribute name="flight" type="xs:IDREF" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="creditcard" type="xs:string" />
</xs:schema>

=== SalmanSiddique/ZorbaXQuery/instances/instance5.xml
<?xml version="1.0" encoding="UTF-8"?>
<travel xmlns="http://tempuri.org/flight"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://tempuri.org/flight file:/D:/MSC/Sem1/Web%20Data%20Management%20and%20XML/Project7/flight.xsd">
    <passenger ssn="ID001">
        <name>name0</name>
        <address>address0</address>
    </passenger>
    <passenger ssn="ID003">
        <name>name1</name>
        <address>address1</address>
    </passenger>
    <reservation passenger="ID002" flight="ID000">
        <creditcard>creditcard0</creditcard>
    </reservation>
    <flight id="ID005" from="ID005" to="ID002">
        <date>date0</date>
        <departureTime>departureTime0</departureTime>
        <arrivalTime>arrivalTime0</arrivalTime>
    </flight>
    <airport code="ID007">
        <name>name2</name>
    </airport>
</travel>

=== SalmanSiddique/ZorbaXQuery/instances/instance3.xml
<?xml version="1.0" encoding="UTF-8"?>
<travel xmlns="http://tempuri.org/flight"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://tempuri.org/flight file:/D:/MSC/Sem1/Web%20Data%20Management%20and%20XML/Project7/flight.xsd">
    <passenger ssn="ID001">
        <name>name0</name>
        <address>address0</address>
    </passenger>
    <airport code="ID003">
        <name>name1</name>
    </airport>
    <passenger ssn="ID005">
        <name>name2</name>
        <address>address1</address>
    </passenger>
    <reservation passenger="ID002" flight="ID002">
        <creditcard>creditcard0</creditcard>
    </reservation>
    <passenger ssn="ID007">
        <name>name3</name>
        <address>address2</address>
    </passenger>
</travel>

=== SalmanSiddique/ZorbaXQuery/instances/instance10.xml
<?xml version="1.0" encoding="UTF-8"?>
<travel xmlns="http://tempuri.org/flight"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://tempuri.org/flight file:/D:/MSC/Sem1/Web%20Data%20Management%20and%20XML/Project7/flight.xsd">
    <airport code="ID001">
        <name>name0</name>
    </airport>
    <flight id="ID003" from="ID003" to="ID001">
        <date>date0</date>
        <departureTime>departureTime0</departureTime>
        <arrivalTime>arrivalTime0</arrivalTime>
    </flight>
    <reservation passenger="ID001" flight="ID002">
        <creditcard>creditcard0</creditcard>
    </reservation>
    <reservation passenger="ID001" flight="ID002">
        <creditcard>creditcard1</creditcard>
    </reservation>
    <airport code="ID005">
        <name>name1</name>
    </airport>
</travel>

=== SalmanSiddique/ZorbaXQuery/instances/instance2.xml
<?xml version="1.0" encoding="UTF-8"?>
<travel xmlns="http://tempuri.org/flight"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://tempuri.org/flight file:/D:/MSC/Sem1/Web%20Data%20Management%20and%20XML/Project7/flight.xsd">
    <reservation passenger="ID002" flight="ID003">
        <creditcard>creditcard0</creditcard>
    </reservation>
    <passenger ssn="ID002">
        <name>name0</name>
        <address>address0</address>
    </passenger>
    <reservation passenger="ID002" flight="ID003">
        <creditcard>creditcard1</creditcard>
    </reservation>
    <airport code="ID001">
        <name>name1</name>
    </airport>
    <reservation passenger="ID001" flight="ID002">
        <creditcard>creditcard2</creditcard>
    </reservation>
</travel>

=== SalmanSiddique/ZorbaXQuery/instances/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<travel xmlns="http://tempuri.org/flight"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://tempuri.org/flight file:/D:/MSC/Sem1/Web%20Data%20Management%20and%20XML/Project7/flight.xsd">
    <airport code="ID001">
        <name>name0</name>
    </airport>
    <airport code="ID003">
        <name>name1</name>
    </airport>
    <reservation passenger="ID002" flight="ID000">
        <creditcard>creditcard0</creditcard>
    </reservation>
    <airport code="ID005">
        <name>name2</name>
    </airport>
    <passenger ssn="ID007">
        <name>name3</name>
        <address>address0</address>
    </passenger>
</travel>
